name: Generate Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch data from GitHub API
        run: |
          echo "Fetching data..."
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               https://api.github.com/users/YOUR_USERNAME > public/data.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data.json
          git commit -m "Update data.json"
          git push
